In [11]:
import pandas as pd
import json

In [12]:
path = '../data/weather_data.json'

In [13]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [14]:
with open(path) as f:
    data = json.load(f) #Transformar dict objeto python

df = pd.json_normalize(data)

df.head()

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,rain.1h,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset
0,"[{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}]",stations,6844,1785189465,-10800,3456068,Novo Hamburgo,200,-51.1306,-29.6783,18.31,18.68,18.17,20.46,1011,95,1011,997,0.74,290,1.02,3.45,94,2,2020383,BR,1785147154,1785185355

In [ ]:
timestamp = df["dt"]
offset = df["timezone"]


from datetime import datetime, UTC, timedelta,timezone

local_dt = datetime.fromtimestamp(timestamp, tz=UTC).astimezone(timezone(timedelta(seconds=offset)))

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,wind.gust,rain.1h,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset
0,"[{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10n'}]",stations,6844,27/07/2026 21:57,-10800,3456068,Novo Hamburgo,200,-51.1306,-29.6783,18.31,18.68,18.17,20.46,1011,95,1011,997,0.74,290,1.02,3.45,94,2,2020383,BR,1785147154,1785185355